[tools]
fzf = "latest"
go = "1.25"
starship = "latest"
stylua = "latest"
tmux = "latest"
node = "latest"
ripgrep = "latest"
bat = "latest"
ffmpeg = "latest"
fd = "latest"
bob = "latest"
uv = "latest"
tree-sitter = "latest"

[settings]
idiomatic_version_file_enable_tools = []
